/**
 * @prettier
 * @description: Constants for actions
 * @author:   Henrik Grönvall
 * @version:  0.0.1
 * @copyright:  Copyright (c) 2017 HGC AB
 * @license: The MIT License (MIT)
 */

export const LOG_STATUS = 'LOG_STATUS'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

// Error branch
export const VALIDATION_ERROR = 'VALIDATION_ERROR'
export const FETCH_VALIDATION_ERROR = 'FETCH_VALIDATION_ERROR'
export const FETCH_ERROR = 'FETCH_ERROR'
export const RESET_ERROR = 'RESET_ERROR'

// isFetching branch
export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_VALIDATION_SUCCESS = 'FETCH_VALIDATION_SUCCESS'


export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS'

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const UPDATE_PROFILE_STATE = 'UPDATE_PROFILE_STATE'

export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'

export const CLIENT_VALIDATION_FAILED = 'CLIENT_VALIDATION_FAILED'
export const CLIENTS_FETCHING = 'CLIENTS_FETCHING'
export const CLIENTS_ERROR = 'CLIENTS_ERROR'
export const CLIENTS_GET_SUCCESS = 'CLIENTS_GET_SUCCESS'
export const CLIENTS_UPDATE_SUCCESS = 'CLIENTS_UPDATE_SUCCESS'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS'
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS'
export const CLIENT_RESET_ERROR = 'CLIENT_RESET_ERROR'
export const CLIENT_SET_SELECTED = 'CLIENT_SET_SELECTED'
export const CLIENT_RESET_SELECTED = 'CLIENT_RESET_SELECTED'
export const CLIENT_UPDATE_STATE = 'CLIENT_UPDATE_STATE'
