/**
 * Description: Constants for actions
 *
 * @author:   Henrik Grönvall
 * @version:  0.0.1
 * @copyright:  Copyright (c) 2017 HGC AB
 * @license: The MIT License (MIT)
 */

export const CREDENTIALS_VALIDATION_FAILED = "CREDENTIALS_VALIDATION_FAILED";
export const FETCH_SESSION_START = "FETCH_SESSION_START";
export const FETCH_SESSION_FAILED = "FETCH_SESSION_FAILED";
export const FETCH_SESSION_SUCCESS = "FETCH_SESSION_SUCCESS";
export const REMOVE_SESSION = "REMOVE_SESSION";
export const UPDATE_CREDENTIALS = "UPDATE_CREDENTIALS";
export const PASSWORD_VISIBLE = "PASSWORD_VISIBLE";
export const RESET_SESSION_ERROR = "RESET_SESSION_ERROR";

export const PROFILE_VALIDATION_FAILED = "PROFILE_VALIDATION_FAILED";
export const FETCH_PROFILE_STARTED = "FETCH_PROFILE_STARTED";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const UPDATE_PROFILE_STATE = "UPDATE_PROFILE_STATE";
export const RESET_PROFILE_ERROR = "RESET_PROFILE_ERROR";