/**
 * Description: Constants for actions
 *
 * @author:   Henrik Grönvall
 * @version:  0.0.1
 * @copyright:  Copyright (c) 2017 HGC AB
 * @license: The MIT License (MIT)
 */

export const LOG_STATUS = "LOG_STATUS";
export const RESET_ERROR = "RESET_ERROR";

export const CREDENTIALS_VALIDATION_FAILED = "CREDENTIALS_VALIDATION_FAILED";
export const FETCH_SESSION_START = "FETCH_SESSION_START";
export const FETCH_SESSION_FAILED = "FETCH_SESSION_FAILED";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const REFRESH_SESSION_SUCCESS = "REFRESH_SESSION_SUCCESS";
export const REMOVE_SESSION = "REMOVE_SESSION";
export const UPDATE_CREDENTIALS_STATE = "UPDATE_CREDENTIALS_STATE";
export const PASSWORD_VISIBLE = "PASSWORD_VISIBLE";
export const RESET_SESSION_ERROR = "RESET_SESSION_ERROR";

export const PROFILE_VALIDATION_FAILED = "PROFILE_VALIDATION_FAILED";
export const FETCH_PROFILE_STARTED = "FETCH_PROFILE_STARTED";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const UPDATE_PROFILE_STATE = "UPDATE_PROFILE_STATE";
export const RESET_PROFILE_ERROR = "RESET_PROFILE_ERROR";

export const USER_VALIDATION_FAILED = "USER_VALIDATION_FAILED";
export const USERS_FETCHING = "USERS_FETCHING";
export const USERS_ERROR = "USERS_ERROR";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_UPDATE_SUCCESS = "USERS_UPDATE_SUCCESS";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_RESET_ERROR = "USER_RESET_ERROR";

export const CLIENT_VALIDATION_FAILED = "CLIENT_VALIDATION_FAILED";
export const CLIENTS_FETCHING = "CLIENTS_FETCHING";
export const CLIENTS_ERROR = "CLIENTS_ERROR";
export const CLIENTS_GET_SUCCESS = "CLIENTS_GET_SUCCESS";
export const CLIENTS_UPDATE_SUCCESS = "CLIENTS_UPDATE_SUCCESS";
export const CLIENT_CREATE_SUCCESS = "CLIENT_CREATE_SUCCESS";
export const CLIENT_UPDATE_SUCCESS = "CLIENT_UPDATE_SUCCESS";
export const CLIENT_DELETE_SUCCESS = "CLIENT_DELETE_SUCCESS";
export const CLIENT_RESET_ERROR = "CLIENT_RESET_ERROR";