/**
 * @prettier
 * @description: Action creator constants
 * @copyright (c) 2018 - present, HGC AB.
 * @licence This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export const LOG_STATUS = 'LOG_STATUS'

export const VALIDATION_ERROR = 'VALIDATION_ERROR'
export const FETCH_VALIDATION_ERROR = 'FETCH_VALIDATION_ERROR'
export const FETCH_ERROR = 'FETCH_ERROR'
export const RESET_ERROR = 'RESET_ERROR'

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'

export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_REFRESH_SESSION_SUCCESS = 'FETCH_REFRESH_SESSION_SUCCESS'
export const REMOVE_SESSION = 'REMOVE_SESSION'

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_UPDATE_SUCCESS = 'FETCH_PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_STATE = 'UPDATE_PROFILE_STATE'

export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'

export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS'
export const FETCH_CLIENT_CREATE_SUCCESS = 'FETCH_CLIENT_CREATE_SUCCESS'
export const FETCH_CLIENT_UPDATE_SUCCESS = 'FETCH_CLIENT_UPDATE_SUCCESS'
export const FETCH_CLIENT_DELETE_SUCCESS = 'FETCH_CLIENT_DELETE_SUCCESS'
export const CLIENT_SET_SELECTED = 'CLIENT_SET_SELECTED'
export const CLIENT_RESET_SELECTED = 'CLIENT_RESET_SELECTED'
export const CLIENT_UPDATE_STATE = 'CLIENT_UPDATE_STATE'
